#step1
FROM node:14.16.0-alpine3.13 as build-stage

#RUN addgroup app && adduser -S -G app app
#USER app
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

#step2
FROM nginx:1.12-alpine
COPY --from=build-stage /app/build /usr/share/nginx/html 
EXPOSE 80 
#CMD ["npm", "start"]
ENTRYPOINT [ "nginx","-g","daemon off;"]