version: "3.8"

services:
  web:
    container_name: web
    depends_on:
      - api
    build: ./frontend
    ports:
      - 3000:3000

  api:
    container_name: api
    depends_on:
      - db
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db:27017/vidly
    # command: ./docker-entrypoint.sh
    volumes:
      - ./backend:/app

  db:
    container_name: db
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
